services:
  cloudflare-ddns:
    build:
      context: .
      dockerfile: Dockerfile
    image: cloudflare-ddns
    volumes:
      - ./app:/app
      - ./app/nginx/nginx.conf:/etc/nginx/sites-available/default
    network_mode: host
    container_name: cloudflare-ddns
    restart: unless-stopped
